use chrono::Utc;
use sentra_core::{DetectionResult, DnsQueryInfo, Evidence, ThreatLevel};
use std::collections::{HashMap, VecDeque};
use uuid::Uuid;

pub struct DnsCache {
    max_entries: usize,
    queries: VecDeque<DnsQueryInfo>,
    query_count_by_domain: HashMap<String, usize>,
}

impl DnsCache {
    pub fn new(max_entries: usize) -> Self {
        Self {
            max_entries,
            queries: VecDeque::with_capacity(max_entries),
            query_count_by_domain: HashMap::new(),
        }
    }

    pub fn record_query(&mut self, query: DnsQueryInfo) {
        if self.queries.len() >= self.max_entries {
            if let Some(old) = self.queries.pop_front() {
                if let Some(count) = self.query_count_by_domain.get_mut(&old.query_name) {
                    *count -= 1;
                    if *count == 0 {
                        self.query_count_by_domain.remove(&old.query_name);
                    }
                }
            }
        }

        *self.query_count_by_domain.entry(query.query_name.clone()).or_insert(0) += 1;
        self.queries.push_back(query);
    }

    pub fn detect_dga(domain: &str) -> bool {
        // Basic Shannon entropy check on the first label
        let parts: Vec<&str> = domain.split('.').collect();
        if parts.is_empty() {
            return false;
        }

        let label = parts[0];
        if label.len() < 10 {
            return false;
        }

        let mut freq = HashMap::new();
        for c in label.chars() {
            *freq.entry(c).or_insert(0) += 1;
        }

        let len = label.len() as f64;
        let mut entropy = 0.0;
        for count in freq.values() {
            let p = *count as f64 / len;
            entropy -= p * p.log2();
        }

        entropy > 3.8
    }

    pub fn detect_tunneling(&self) -> Vec<DetectionResult> {
        let mut results = Vec::new();

        for (domain, &count) in &self.query_count_by_domain {
            if count > 50 {
                // High query volume to the same domain might indicate tunneling
                results.push(DetectionResult {
                    id: Uuid::new_v4(),
                    rule_name: "DNS Tunneling Suspicion".to_string(),
                    threat_level: ThreatLevel::Medium,
                    confidence: 0.6,
                    description: format!("High volume of DNS queries to domain: {}", domain),
                    evidence: vec![Evidence {
                        source: "dns_monitor".to_string(),
                        detail: format!("Query count: {}", count),
                        timestamp: Utc::now(),
                    }],
                    affected_process: None,
                    timestamp: Utc::now(),
                    mitre_technique: Some("T1071.004".to_string()), // Application Layer Protocol: DNS
                });
            } else if Self::detect_dga(domain) {
                results.push(DetectionResult {
                    id: Uuid::new_v4(),
                    rule_name: "DGA Domain Detected".to_string(),
                    threat_level: ThreatLevel::High,
                    confidence: 0.8,
                    description: format!("Domain looks generated by an algorithm: {}", domain),
                    evidence: vec![Evidence {
                        source: "dns_monitor".to_string(),
                        detail: format!("Domain: {}", domain),
                        timestamp: Utc::now(),
                    }],
                    affected_process: None,
                    timestamp: Utc::now(),
                    mitre_technique: Some("T1568.002".to_string()), // Dynamic Resolution: Domain Generation Algorithms
                });
            }
        }

        results
    }
}
