[package]
name = "sentra-agent"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
engine-detection = { path = "../engine-detection" }
engine-etw = { path = "../engine-etw" }
engine-memory = { path = "../engine-memory" }
engine-network = { path = "../engine-network" }
engine-persistence = { path = "../engine-persistence" }
engine-process = { path = "../engine-process" }
engine-remediation = { path = "../engine-remediation" }
serde.workspace = true
shared-ipc = { path = "../shared-ipc" }
shared-models = { path = "../shared-models" }
sentra-ui = { path = "../sentra-ui" }
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
